import type { MachgenModelDef } from './types'

export const MACHGEN_MODELS: MachgenModelDef[] = [
  // ─── Video models ─────────────────────────────────────────────────────────
  {
    id: 'Wan2.2-A14B',
    name: 'Wan2.2-A14B (MachGen)',
    category: 'Wan',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [480, 720],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    allowedDurations: [5, 6, 8, 10],
    defaultFps: 16,
    defaultInferSteps: 30,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.018 },
      { resolution: '720p', height: 720, costPerSec: 0.036 },
    ],
  },
  {
    id: 'LTX-2.3-Pro',
    name: 'LTX-2.3-Pro (MachGen)',
    category: 'Lightricks',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [540, 720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
    allowedDurations: [5, 6, 8, 10],
    defaultFps: 24,
    prices: [
      { resolution: '540p', height: 540, costPerSec: 0.008 },
      { resolution: '720p', height: 720, costPerSec: 0.015 },
      { resolution: '1080p', height: 1080, costPerSec: 0.03 },
    ],
  },
  {
    id: 'Vidu-Q3-Turbo',
    name: 'Vidu-Q3-Turbo (MachGen)',
    category: 'Vidu',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [4, 8],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.03 },
      { resolution: '1080p', height: 1080, costPerSec: 0.06 },
    ],
  },
  {
    id: 'Vidu-Q3-Pro',
    name: 'Vidu-Q3-Pro (MachGen)',
    category: 'Vidu',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [4, 8],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.04 },
      { resolution: '1080p', height: 1080, costPerSec: 0.08 },
    ],
  },
  {
    id: 'MiniMax-H3',
    name: 'MiniMax H3 (MachGen)',
    category: 'MiniMax',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V', 'R2V', 'UPSCALE'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true, // Supports lone end frame keyframe_indices: [-1]
    supportsR2V: true,
    supportsUpscale: true, // Accepts 768p outputs, returns 2K
    supportsVideoRef: true,
    supportsAudioRef: false,
    allowedHeights: [480, 768, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9', 'adaptive'],
    allowedDurations: [5, 6, 8, 10, 12, 15],
    defaultFps: 24,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.035 },
      { resolution: '768p', height: 768, costPerSec: 0.04 },
      { resolution: '1080p', height: 1080, costPerSec: 0.08 },
    ],
  },
  {
    id: 'MiniMax-H3-Turbo',
    name: 'MiniMax H3 Turbo (MachGen)',
    category: 'MiniMax',
    hosting: 'MachGen',
    supportedTasks: ['T2V', 'I2V', 'R2V', 'UPSCALE'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: true,
    supportsVideoRef: true,
    supportsAudioRef: false,
    allowedHeights: [480, 768, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9', 'adaptive'],
    allowedDurations: [5, 6, 8, 10, 12, 15],
    defaultFps: 24,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.015 },
      { resolution: '768p', height: 768, costPerSec: 0.020 },
      { resolution: '1080p', height: 1080, costPerSec: 0.040 },
    ],
  },
  {
    id: 'Seedance-2.5',
    name: 'Seedance 2.5 (MachGen)',
    category: 'ByteDance',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.05 },
      { resolution: '1080p', height: 1080, costPerSec: 0.09 },
    ],
  },
  {
    id: 'Seedance-2.0',
    name: 'Seedance 2.0 (MachGen)',
    category: 'ByteDance',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.04 },
      { resolution: '1080p', height: 1080, costPerSec: 0.07 },
    ],
  },
  {
    id: 'Seedance-2.0-Fast',
    name: 'Seedance 2.0 Fast (MachGen)',
    category: 'ByteDance',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.025 }],
  },
  {
    id: 'Seedance-2.0-Mini',
    name: 'Seedance 2.0 Mini (MachGen)',
    category: 'ByteDance',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.02 }],
  },
  {
    id: 'Kling-v3',
    name: 'Kling-v3 (MachGen)',
    category: 'Kling',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.06 },
      { resolution: '1080p', height: 1080, costPerSec: 0.10 },
    ],
  },
  {
    id: 'Kling-o3',
    name: 'Kling-o3 (MachGen)',
    category: 'Kling',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.07 },
      { resolution: '1080p', height: 1080, costPerSec: 0.12 },
    ],
  },
  {
    id: 'Vidu-Q3',
    name: 'Vidu-Q3 (MachGen)',
    category: 'Vidu',
    hosting: 'Partner',
    supportedTasks: ['R2V'],
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [4, 8],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.035 }],
  },
  {
    id: 'Vidu-Q3-Pro-Fast',
    name: 'Vidu-Q3-Pro-Fast (MachGen)',
    category: 'Vidu',
    hosting: 'Partner',
    supportedTasks: ['I2V'],
    supportsT2V: false,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [4, 8],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.03 }],
  },
  {
    id: 'Alibaba-Wan-3.0',
    name: 'Alibaba-Wan-3.0 (MachGen)',
    category: 'Wan',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10, 15],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.04 },
      { resolution: '1080p', height: 1080, costPerSec: 0.08 },
    ],
  },
  {
    id: 'Veo-3.1',
    name: 'Veo-3.1 (MachGen)',
    category: 'Google',
    hosting: 'Partner',
    supportedTasks: ['T2V'],
    supportsT2V: true,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.15 },
      { resolution: '1080p', height: 1080, costPerSec: 0.25 },
    ],
  },
  {
    id: 'Veo-3.1-Fast',
    name: 'Veo-3.1-Fast (MachGen)',
    category: 'Google',
    hosting: 'Partner',
    supportedTasks: ['T2V'],
    supportsT2V: true,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.09 }],
  },
  {
    id: 'Pixverse-V6',
    name: 'Pixverse-V6 (MachGen)',
    category: 'Pixverse',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 8],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.04 },
      { resolution: '1080p', height: 1080, costPerSec: 0.08 },
    ],
  },
  {
    id: 'Pixverse-C1',
    name: 'Pixverse-C1 (MachGen)',
    category: 'Pixverse',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 8],
    defaultFps: 24,
    prices: [
      { resolution: '720p', height: 720, costPerSec: 0.05 },
      { resolution: '1080p', height: 1080, costPerSec: 0.09 },
    ],
  },
  {
    id: 'HappyHorse-1.1',
    name: 'HappyHorse-1.1 (MachGen)',
    category: 'HappyHorse',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.035 }],
  },
  {
    id: 'HappyHorse-1.0',
    name: 'HappyHorse-1.0 (MachGen)',
    category: 'HappyHorse',
    hosting: 'Partner',
    supportedTasks: ['T2V', 'I2V', 'R2V'],
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: true,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.025 }],
  },
  {
    id: 'Grok-Imagine-Video',
    name: 'Grok-Imagine-Video (MachGen)',
    category: 'xAI',
    hosting: 'Partner',
    supportedTasks: ['T2V'],
    supportsT2V: true,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.05 }],
  },
  {
    id: 'Grok-Imagine-Video-1.5',
    name: 'Grok-Imagine-Video-1.5 (MachGen)',
    category: 'xAI',
    hosting: 'Partner',
    supportedTasks: ['I2V'],
    supportsT2V: false,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.06 }],
  },
  {
    id: 'Topaz-Video-Precision',
    name: 'Topaz-Video-Precision (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: true,
    allowedHeights: [1080, 2160],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '4K', height: 2160, costPerSec: 0.05 }],
  },
  {
    id: 'Topaz-Video-Precision-Animation',
    name: 'Topaz-Video-Precision-Animation (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: true,
    allowedHeights: [1080, 2160],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '4K', height: 2160, costPerSec: 0.05 }],
  },
  {
    id: 'Topaz-Video-Generative',
    name: 'Topaz-Video-Generative (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: true,
    allowedHeights: [1080, 2160],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '4K', height: 2160, costPerSec: 0.06 }],
  },
  {
    id: 'Topaz-Video-Generative-Fast',
    name: 'Topaz-Video-Generative-Fast (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: true,
    allowedHeights: [1080, 2160],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10],
    defaultFps: 24,
    prices: [{ resolution: '4K', height: 2160, costPerSec: 0.04 }],
  },

  // ─── Image models ─────────────────────────────────────────────────────────
  {
    id: 'FLUX.2-dev',
    name: 'FLUX.2 Dev (MachGen)',
    category: 'Flux',
    hosting: 'MachGen',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.025 }],
  },
  {
    id: 'HiDream-O1-Image',
    name: 'HiDream-O1-Image (MachGen)',
    category: 'HiDream',
    hosting: 'MachGen',
    supportedTasks: ['T2I'],
    supportsT2I: true,
    supportsI2I: false,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.020 }],
  },
  {
    id: 'Topaz-Image-Precision',
    name: 'Topaz-Image-Precision (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2I: false,
    supportsI2I: false,
    supportsUpscale: true,
    allowedHeights: [2048, 4096],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '4K', height: 4096, cost: 0.020 }],
  },
  {
    id: 'Topaz-Image-Generative',
    name: 'Topaz-Image-Generative (MachGen)',
    category: 'Topaz',
    hosting: 'Partner',
    supportedTasks: ['UPSCALE'],
    supportsT2I: false,
    supportsI2I: false,
    supportsUpscale: true,
    allowedHeights: [2048, 4096],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '4K', height: 4096, cost: 0.025 }],
  },
  {
    id: 'Grok-Imagine-Image',
    name: 'Grok-Imagine-Image (MachGen)',
    category: 'xAI',
    hosting: 'Partner',
    supportedTasks: ['T2I'],
    supportsT2I: true,
    supportsI2I: false,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.015 }],
  },
  {
    id: 'Grok-Imagine-Image-Quality',
    name: 'Grok-Imagine-Image-Quality (MachGen)',
    category: 'xAI',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.025 }],
  },
  {
    id: 'Nano-Banana-2',
    name: 'Nano-Banana-2 (MachGen)',
    category: 'Google',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.020 }],
  },
  {
    id: 'Nano-Banana-Pro',
    name: 'Nano-Banana-Pro (MachGen)',
    category: 'Google',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.035 }],
  },
  {
    id: 'Seedream-5.0-lite',
    name: 'Seedream-5.0-lite (MachGen)',
    category: 'ByteDance',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.015 }],
  },
  {
    id: 'GPT-Image-2',
    name: 'GPT-Image-2 (MachGen)',
    category: 'OpenAI',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.030 }],
  },
  {
    id: 'GPT-Image-2.5-Sunburst',
    name: 'GPT-Image-2.5-Sunburst (MachGen)',
    category: 'OpenAI',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.040 }],
  },
  {
    id: 'GPT-Image-2.5-Flare',
    name: 'GPT-Image-2.5-Flare (MachGen)',
    category: 'OpenAI',
    hosting: 'Partner',
    supportedTasks: ['T2I', 'I2I'],
    supportsT2I: true,
    supportsI2I: true,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, cost: 0.045 }],
  },

  // ─── Audio models ─────────────────────────────────────────────────────────
  {
    id: 'Eleven-v3',
    name: 'Eleven-v3 (MachGen)',
    category: 'ElevenLabs',
    hosting: 'Partner',
    supportedTasks: ['T2S', 'T2D'],
    supportsT2S: true,
    supportsT2D: true,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', cost: 0.005 }],
  },
  {
    id: 'Eleven-SFX-v2',
    name: 'Eleven-SFX-v2 (MachGen)',
    category: 'ElevenLabs',
    hosting: 'Partner',
    supportedTasks: ['T2SFX'],
    supportsT2SFX: true,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', cost: 0.005 }],
  },
  {
    id: 'Eleven-Music-v2',
    name: 'Eleven-Music-v2 (MachGen)',
    category: 'ElevenLabs',
    hosting: 'Partner',
    supportedTasks: ['T2M'],
    supportsT2M: true,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', cost: 0.008 }],
  },
]

const ALIASES: Record<string, string> = {
  'kling-3-0': 'Kling-v3',
  'wan-3-0': 'Alibaba-Wan-3.0',
  'flux-dev': 'FLUX.2-dev',
  'flux-schnell': 'FLUX.2-dev',
  'flux-2-pro': 'FLUX.2-dev',
  'kokoro-82m': 'Eleven-v3',
  'fish-speech': 'Eleven-v3',
  'stable-audio': 'Eleven-Music-v2',
}

export function getMachgenModel(modelOrId?: string): MachgenModelDef | undefined {
  if (!modelOrId) return undefined
  const clean = modelOrId.replace(/^machgen\//, '').replace(/\/(t2v|i2v|fflf|ref|upscale|t2i|i2i|t2s|t2d|t2sfx|t2m)$/, '').trim()
  const lower = clean.toLowerCase()
  const targetId = ALIASES[lower] || clean
  return MACHGEN_MODELS.find(
    m =>
      m.id.toLowerCase() === targetId.toLowerCase() ||
      m.name.toLowerCase() === targetId.toLowerCase() ||
      m.id.toLowerCase() === clean.toLowerCase() ||
      m.name.toLowerCase() === clean.toLowerCase()
  )
}
