import type { MachgenModelDef } from './types'

export const MACHGEN_MODELS: MachgenModelDef[] = [
  {
    id: 'MiniMax-H3',
    name: 'MiniMax H3 (MachGen)',
    category: 'MiniMax',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true, // Also supports lone end frame keyframe_indices: [-1]
    supportsR2V: true,
    supportsUpscale: true,
    supportsVideoRef: true,
    supportsAudioRef: true,
    allowedHeights: [480, 768, 1440],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9', 'adaptive'],
    allowedDurations: [5, 6, 8, 10, 12, 15],
    defaultFps: 24,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.035 },
      { resolution: '768p', height: 768, costPerSec: 0.04 },
      { resolution: '1440p', height: 1440, costPerSec: 0.10 },
    ],
  },
  {
    id: 'MiniMax-H3-Turbo',
    name: 'MiniMax H3 Turbo (MachGen)',
    category: 'MiniMax',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: true,
    supportsUpscale: true,
    supportsVideoRef: true,
    supportsAudioRef: true,
    allowedHeights: [480, 768, 1440],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9', 'adaptive'],
    allowedDurations: [5, 6, 8, 10, 12, 15],
    defaultFps: 24,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.015 },
      { resolution: '768p', height: 768, costPerSec: 0.020 },
      { resolution: '1440p', height: 1440, costPerSec: 0.050 },
    ],
  },
  {
    id: 'LTX-2.3-Pro',
    name: 'LTX-2.3-Pro (MachGen)',
    category: 'Lightricks',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true, // start + end frame [0, -1]
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [540, 720, 1080],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
    allowedDurations: [5, 6, 8, 10],
    defaultFps: 24,
    prices: [
      { resolution: '540p', height: 540, costPerSec: 0.008 },
      { resolution: '720p', height: 720, costPerSec: 0.015 },
      { resolution: '1080p', height: 1080, costPerSec: 0.03 },
    ],
  },
  {
    id: 'Wan2.2-A14B',
    name: 'Wan2.2-A14B (MachGen)',
    category: 'Wan',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [480, 720],
    allowedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    allowedDurations: [5, 6, 8, 10],
    defaultFps: 16,
    defaultInferSteps: 30,
    prices: [
      { resolution: '480p', height: 480, costPerSec: 0.018 },
      { resolution: '720p', height: 720, costPerSec: 0.036 },
    ],
  },
  {
    id: 'kling-3-0',
    name: 'Kling 3.0 (MachGen)',
    category: 'Kling',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: true,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10, 15],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.06 }],
  },
  {
    id: 'wan-3-0',
    name: 'Wan 3.0 (MachGen)',
    category: 'Wan',
    hosting: 'MachGen',
    supportsT2V: true,
    supportsI2V: true,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [720],
    allowedAspectRatios: ['16:9', '9:16', '1:1'],
    allowedDurations: [5, 10, 15],
    defaultFps: 24,
    prices: [{ resolution: '720p', height: 720, costPerSec: 0.035 }],
  },
  {
    id: 'flux-dev',
    name: 'FLUX.1 Dev (MachGen)',
    category: 'Flux',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, costPerSec: 0.015 }],
  },
  {
    id: 'flux-schnell',
    name: 'FLUX.1 Schnell (MachGen)',
    category: 'Flux',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, costPerSec: 0.002 }],
  },
  {
    id: 'flux-2-pro',
    name: 'FLUX.2 Pro (MachGen)',
    category: 'Flux',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [1024],
    allowedAspectRatios: ['1:1', '16:9', '9:16'],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: '1K', height: 1024, costPerSec: 0.030 }],
  },
  {
    id: 'kokoro-82m',
    name: 'Kokoro-82M (MachGen)',
    category: 'Kokoro',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', height: 0, costPerSec: 0.005 }],
  },
  {
    id: 'fish-speech',
    name: 'Fish-Speech (MachGen)',
    category: 'Fish',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', height: 0, costPerSec: 0.010 }],
  },
  {
    id: 'stable-audio',
    name: 'Stable Audio Open (MachGen)',
    category: 'Stability',
    hosting: 'MachGen',
    supportsT2V: false,
    supportsI2V: false,
    supportsEndFrame: false,
    supportsR2V: false,
    supportsUpscale: false,
    allowedHeights: [],
    allowedAspectRatios: [],
    allowedDurations: [],
    defaultFps: 0,
    prices: [{ resolution: 'clip', height: 0, costPerSec: 0.005 }],
  },
]

export function getMachgenModel(modelOrId?: string): MachgenModelDef | undefined {
  if (!modelOrId) return undefined
  const clean = modelOrId.replace(/^machgen\//, '').replace(/\/(t2v|i2v|fflf|ref|upscale)$/, '')
  return MACHGEN_MODELS.find(m => m.id.toLowerCase() === clean.toLowerCase() || m.name.toLowerCase() === clean.toLowerCase() || m.id.toLowerCase() === modelOrId.toLowerCase())
}
